.TH WAVPLAY 1
.SH NAME
wavplay, wavrec \- play and record WAV files
.SH SYNOPSIS
.B wavplay
.RB [ -h, --help ]
.RB [ -q ]
.RB [ -s
.IR rate ]
.RB [ -S ]
.RB [ -M ]
.RB [ -b
.IR bits ]
.RB [ -i ]
.RB [ -k
.IR ipc-key ]
.RB [ -R ]
.RB [ -l ]
.RB [ -u ]
.RB [ -L ]
.RB [ -U ]
.RB [ -V, --version ]
.RI [ input-files ]
.PP
.B wavrec
.RB [ -h, --help ]
.RB [ -q ]
.RB [ -s
.IR rate ]
.RB [ -S ]
.RB [ -M ]
.RB [ -b
.IR bits ]
.RB [ -t
.IR secs ]
.RB [ -k
.IR ipc-key ]
.RB [ -R ]
.RB [ -l ]
.RB [ -u ]
.RB [ -L ]
.RB [ -U ]
.RB [ -V, --version ]
.RI [ output-file ]
.PP
.SH DESCRIPTION
.B wavplay
plays a WAV format file to the audio device (by default
.B /dev/dsp
) reading WAV parameters from the input file header.  
(Command-line options will
override these defaults, if you know better or for special effects.)
.PP
.B wavrec
samples the audio device and writes a WAV file.  Command-line options
provide complete control over the resolution and duration of sampling.
.PP
Both
.B wavplay
and
.B wavrec
allow the audio device to be locked for exclusive access.

.SH OPTIONS
.TP
.BI \-h
print a short summary of options.
.TP
.BI \--help
same as -h.
.TP
.BI \-q
quiet mode, suppress messages.
.TP
.BI \-s " rate"
set sampling rate in Hz.  The default is 8000 Hz.
.TP
.BI \-S
set stereo mode (overrides -M).  This is the default.
.TP
.BI \-M
set mono mode (overrides -S).
.TP
.BI \-b " bits"
set the number of bits per sample (8/12/16).  The default is 16.
.TP
.BI \-t " secs"
set time limit for recording.  The default is 10 seconds.
.TP
.BI \-i
don't play, just display WAV file header information.
.TP
.BI \-k " key"
specify the IPC key for device-locking semaphores.  The default is 0x33333333.
.TP
.BI \-R
remove and recreate device-locking semaphores.
.TP
.BI \-l
lock the audio device for playing.
.TP
.BI \-u
unlock the audio device for playing.
.TP
.BI \-L
lock the audio device for recording.
.TP
.BI \-U
unlock the audio device for recording.
.TP
.BI \-V
display version and copyright information.
.TP
.BI \--version
same as -V.

.SH BUGS
.B wavplay
will not play files which contain SLNT or LIST chunks.
.PP
Compressed formats are not currently supported.

.SH AUTHOR
.B wavplay 
was almost totally rewritten for version 1.0 by Warren W. 
Gay (wwg@ica.net) replacing earlier code by Andre Fuechsel 
(af1@irz.inf.tu-dresden.de).  Erik 
de Castro Lopo (erikd@zip.com.au) wrote the WAV header I/O routines.
This manual page was written by Stephen Crane (jsc@cs.city.ac.uk).

.SH "SEE ALSO"
xltwavplay(1)

.SH DATE
12 June 1997
